### ISSUE TITLE
Unable to use custom login and password during installation

### ISSUE THREAD

**Issue by owlet1997** [cuba-platform/cuba-sdk#81]
**Environment:**
CUBA SDK 1.0.5
Ubuntu 20.04 LTS 
Windows 10

**TC:**
1. Install the last version of a CUBA SDK
2. Use any custom login and password (user/user e.g.) during `setup-nexus` installation

**AR:**
the repository is started but user has no access in the browser 
![image](https://user-images.githubusercontent.com/45730069/155987453-3d8a550b-ca6e-4490-8ee4-fb332718c942.png)
![image](https://user-images.githubusercontent.com/45730069/155987541-0bbf8529-fb43-4472-8aed-dd606663479d.png)

if the `admin`/`admin` credentials were used the problems does not appear

**Comment by artemglinov** [comment]
Probably, the problem is caused by the inconsistency between the login + password ""admin" + <password stored in the <repository-path>/sonatype-work/nexus3/admin.password file>" and credentials entered by the user in the command line (see SetupNexusCommand#configureNexus function for more details), i.e. the repository is configured with the former credentials and then requested with the latter.
